# Reference https://gist.github.com/Virolea/b589e7bd128ed53b9080583d1213e71f
# Reference https://robots.thoughtbot.com/circleci-2-rails
version: 2
jobs:
  build-api:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          RAILS_ENV: test
          BUNDLER_VERSION: 2.0.1

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: runner
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: ""

      - image: redis:4.0.6

    working_directory: api

    steps:
      - checkout

      - run:
          name: Update Bundler
          command: |
            gem update bundler
      - restore_cache:
          name: Restore Bundler Cache
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: Install Bundler dependencies
          command: |
            sudo apt-get install -y cmake
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          name: Save Bundler Cache
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}


      - run:
          name: Rails tests
          command: |
            cp config/database.yml.ci config/database.yml
            bundle exec rake db:create
            bundle exec rails db:schema:load
            bundle exec rake test

  deploy-api:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-api
      - deploy-api:
          requires:
            - build-api
          filters:
            branches:
              only: master